# Generated by Django 5.2.1 on 2025-06-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='telegram_verification_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Telegram uchun tasdiq kodi'),
        ),
    ]
