# Generated by Django 5.2.1 on 2025-08-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_darsjadvali_izoh'),
        ('users', '0002_alter_studentprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='assigned_groups',
            field=models.ManyToManyField(blank=True, related_name='tyutors', to='tests.group', verbose_name='Ajratilgan guruhlar'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.png', null=True, upload_to='profile_pictures/', verbose_name='Profil rasmi'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='rol',
            field=models.CharField(choices=[('TALABA', 'Talaba'), ('PEDAGOG', 'Pedagog'), ('TYUTOR', 'Tyutor'), ('ADMIN', 'Admin')], default='TALABA', max_length=50, verbose_name='Roli'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True, verbose_name='ID raqami'),
        ),
    ]
