# Generated by Django 5.2.1 on 2025-08-20 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=500, verbose_name='Javob matni')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
            ],
            options={
                'verbose_name': 'Javob Varianti',
                'verbose_name_plural': 'Javob Variantlari',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('status', models.CharField(choices=[('present', '+'), ('absent', '-'), ('partial', 'Qisman')], default='present', max_length=10)),
                ('missed_lessons', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qoldirilgan darslar')),
                ('total_lessons', models.PositiveIntegerField(blank=True, null=True, verbose_name='Jami darslar')),
            ],
            options={
                'verbose_name': 'Davomat Yozuvi',
                'verbose_name_plural': 'Davomat Yozuvlari',
                'permissions': [('can_manage_attendance', 'Can manage student attendance')],
            },
        ),
        migrations.CreateModel(
            name='Bildirishnoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField(verbose_name='Matn')),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
            },
        ),
        migrations.CreateModel(
            name='DarsJadvali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xona', models.CharField(blank=True, max_length=50, null=True, verbose_name='Xona')),
                ('boshlanish_vaqti', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('tugash_vaqti', models.TimeField(verbose_name='Tugash vaqti')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
            ],
            options={
                'verbose_name': 'Dars Jadvali',
                'verbose_name_plural': 'Dars Jadvallari',
            },
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, unique=True, verbose_name='Fan nomi')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Guruh nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Savol matni')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Talabaning javobi',
                'verbose_name_plural': 'Talabalarning javoblari',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name="To'plangan ball")),
                ('completion_time', models.DateTimeField(auto_now_add=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Baho')),
                ('grade_color', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Test Natijasi',
                'verbose_name_plural': 'Test Natijalari',
            },
        ),
        migrations.CreateModel(
            name='TestSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Test sarlavhasi')),
                ('tavsif', models.TextField(blank=True, default='', null=True, verbose_name='Tavsif')),
                ('davomiyligi', models.IntegerField(default=0, verbose_name='Davomiyligi (daqiqa)')),
                ('num_questions', models.PositiveIntegerField(default=0, verbose_name='Savollar soni')),
                ('test_date', models.DateField(default=datetime.date.today, verbose_name='Test sanasi')),
                ('start_time', models.TimeField(default=datetime.time(9, 0), verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(default=datetime.time(10, 0), verbose_name='Tugash vaqti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Test Jadvali',
                'verbose_name_plural': 'Test Jadvallari',
                'ordering': ['test_date', 'start_time'],
            },
        ),
    ]
