# Generated by Django 5.2.1 on 2025-08-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='darsjadvali',
            name='izoh',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
    ]
