# Generated by Django 5.2.1 on 2025-06-15 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, unique=True, verbose_name='Fan nomi')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='DarsJadvali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xona', models.CharField(max_length=50, verbose_name='Xona')),
                ('hafta_kuni', models.CharField(choices=[('Dushanba', 'Dushanba'), ('Seshanba', 'Seshanba'), ('Chorshanba', 'Chorshanba'), ('Payshanba', 'Payshanba'), ('Juma', 'Juma'), ('Shanba', 'Shanba')], max_length=10, verbose_name='Hafta kuni')),
                ('boshlanish_vaqti', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('tugash_vaqti', models.TimeField(verbose_name='Tugash vaqti')),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.group', verbose_name='Guruh')),
                ('oqtuvchi', models.ForeignKey(limit_choices_to={'rol': 'PEDAGOG'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.fan', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Dars Jadvali',
                'verbose_name_plural': 'Dars Jadvallari',
            },
        ),
        migrations.CreateModel(
            name='Davomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(verbose_name='Sana')),
                ('holat', models.CharField(choices=[('keldi', '+ (Keldi)'), ('kelmadi', '- (Kelmadi)'), ('kechikdi', 'Kechikdi')], max_length=10, verbose_name='Holat')),
                ('izoh', models.CharField(blank=True, help_text="Agar kechikkan bo'lsa, sababini yoki vaqtini yozing (masalan, '15 daqiqa').", max_length=50, verbose_name='Izoh')),
                ('dars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.darsjadvali', verbose_name='Dars')),
                ('talaba', models.ForeignKey(limit_choices_to={'rol': 'TALABA'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomatlar',
            },
        ),
    ]
