# Generated by Django 5.2.1 on 2025-06-15 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_fan_darsjadvali_davomat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('status', models.CharField(choices=[('present', '+'), ('absent', '-'), ('partial', 'Qisman')], default='present', max_length=10)),
                ('missed_lessons', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qoldirilgan darslar soni')),
                ('total_lessons', models.PositiveIntegerField(blank=True, null=True, verbose_name='Jami darslar soni')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Davomat Yozuvi',
                'verbose_name_plural': 'Davomat Yozuvlari',
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='Davomat',
        ),
    ]
