# Generated by Django 5.2.1 on 2025-06-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_attendancerecord_delete_davomat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='missed_lessons',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Qoldirilgan darslar'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='total_lessons',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Jami darslar'),
        ),
    ]
