# Generated by Django 5.2.1 on 2025-06-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_attendancerecord_missed_lessons_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'permissions': [('can_manage_attendance', 'Can manage student attendance')], 'verbose_name': 'Davomat Yozuvi', 'verbose_name_plural': 'Davomat Yozuvlari'},
        ),
    ]
